cell:
  g:
    init: 0.001
    max: 6.0e-07
    min: 2.0e-07
    step: 1.0e-07
  hudu:
    init: 0.001
    max: 180
    min: 30
    step: 15
  r:
    init: 3.0e-08
    max: 3.2e-07
    min: 1.2e-07
    step: 2.0e-08
  rr:
    init: 0.001
    max: 2.0e-08
    min: 5.0e-09
    step: 5.0e-09
  zeta:
    init: 0.001
    max: 180
    min: 0
    step: 20

export:
  dir: "exports/0"
  # 哪些导出关键字要进行采样压缩，只要含有关键字的导出标签都会被计算，请写成列表形式，注意 - 和 " 之间有空格
  sample_keys: 
    - "flied"
    # - "bd"
    # - "export_foo"
    # - "..."

train:
  epoch: 50
  batch_size: 32
  hidden_layers: 6
  lr: 1e-2
  weight_decay: 0
  early_stop: 5
  threshold: 0.2
  mse_norm: 1e26
  dropout: 0.1
  loss_weight: 
    - 1
    - 1
  params_norm_dict:
    r: 32e-8
    hudu: 180
    zeta: 180
    g: 6e-7
    rr: 3e-8

dataset:
  type: "bd"
  sampler: 10_points # six_points, four_points, field, lowest, field_single, field, single_point, 10_points, single_point_wo_rr
  bad_data_filter: True
  feature: mse