cell:
  p:
    init: 0.0005
    max: 0.002
    min: 0.0005
    step: 0.0002
  r:
    init: 0.001
    max: 0.003
    min: 0.001
    step: 0.001
  rr:
    init: 0.001
    max: 0.005
    min: 0.001
    step: 0.001