cell:
  r:
    init: 0.00000003
    max: 32e-8
    min: 1e-7
    step: 1e-8
  hudu:
    init: 0.001
    max: 180
    min: 5
    step: 20
  zeta:
    init: 0.001
    max: 180
    min: 0
    step: 20
  g:
    init: 0.001
    max: 6e-7
    min: 1e-7
    step: 1e-7
  rr:
    init: 0.001
    max: 3e
    min: 5e-9
    step: 5e-9

export:
  dir: "exports/0"
  # 哪些导出关键字要进行采样压缩，只要含有关键字的导出标签都会被计算，请写成列表形式，注意 - 和 " 之间有空格
  sample_keys: 
    - "flied"
    # - "bd"
    # - "export_foo"
    # - "..."

train:
  epoch: 200
  batch_size: 16
  lr: 0.0001
  early_stop: 30
  threshold: 0.6
  mse_norm: 1e26
  loss_weight: 
    - 1
    - 1
  params_norm_dict:
    r: 32e-8
    hudu: 180
    zeta: 180
    g: 6e-7
    rr: 3e-8

dataset:
  sampler: field # six_points, four_points, field