cell:
  zeta:
    init: 0.0005
    max: 180
    min: 0
    step: 30
  rr:
    init: 0.001
    max: 0.0045
    min: 0.0035
    step: 0.0005
  rrr:
    init: 0.001
    max: 0.003
    min: 0.001
    step: 0.001

train:
  epoch: 300
  batch_size: 8
  lr: 0.001