name: Package exe with PyInstaller - Windows

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'src/comsol/cmdline.py'
          requirements: 'requirements.txt'
          exe_path: 'dist/windows'
          upload_exe_with_name: 'consol_CLI'
          options: --onefile, --name "consol_CLI"
      - name: create release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag: ${{ github.event.head_commit.message }}
          # name: ${{ github.event.head_commit.message }}
          body: |
            Test Release v1.0.0
          draft: false
          prerelease: false
          allowUpdates: true
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/windows/consol_CLI.exe
            dist/windows/README.md